name: ubuntu-plus-k8s
summary: "ubuntu operating system"
description: "A ubuntu charm with a dispatch hook and a few actions."
maintainer: "juju-qa juju-qa@lists.canonical.com"
tags:
  - "ubuntu"
provides:
  ubuntu:
    interface: ubuntu
resources:
  ubuntu_image:
    type: "oci-image"
    description: "Image used for ubuntu pod."
series:
  - kubernetes
