name: "Client Tests"
on: [push, pull_request]
jobs:

  test-client-ubuntu:
    name: "Client Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macOS-latest is disabled because there is an issue of the tests timing
        # out. No effort has been done to work out why they currently timeout
        # on macOS, but we should investigate that to improve our coverage on
        # other clients.
        # To turn on macOS, just update the os to include it.
        # os: [ubuntu-latest, macOS-latest]
        os: [ubuntu-latest]

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        echo "##[set-env name=GOPATH;]$GITHUB_WORKSPACE"
        echo "##[add-path]$GITHUB_WORKSPACE/bin"
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: src/github.com/juju/juju

    - name: "Install Mongo Dependencies: ubuntu-latest"
      if: (matrix.os == 'ubuntu-latest')
      working-directory: src/github.com/juju/juju
      run: |
        # Remove the default mongo
        sudo rm /etc/apt/sources.list.d/mongodb-org-4.2.list
        sudo DEBIAN_FRONTEND=noninteractive apt-get purge -y mongodb-org
        sudo DEBIAN_FRONTEND=noninteractive apt autoremove
        sudo rm -rf /usr/bin/mongo* || true

        make install-mongo-dependencies

    - name: "Install Mongo Dependencies: macOS-latest"
      if: (matrix.os == 'macOS-latest')
      working-directory: src/github.com/juju/juju
      run: |
        curl -o mongodb-3.6.14.tgz https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.6.14.tgz
        tar xzvf mongodb-3.6.14.tgz
        sudo mkdir -p /usr/local/mongodb
        sudo mv mongodb-osx-x86_64-3.6.14/bin/* /usr/local/mongodb
        sudo mkdir -p /user/local/bin
        sudo ln -s /usr/local/mongodb/mongod /usr/local/bin/mongod
      shell: bash

    - name: Install Vendor Dependencies
      working-directory: src/github.com/juju/juju
      run: |
        make dep
      shell: bash

    - name: Test client
      working-directory: src/github.com/juju/juju
      run: |
        # Jenkins can perform the full jujud testing.
        go test -v ./cmd/juju/... -check.v
        go test -v ./cmd/plugins/... -check.v
